# Generated by Django 5.2.3 on 2025-06-19 02:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articulos', '0002_categoria_articulos_author_articulos_categories'),
    ]

    operations = [
        migrations.RenameField(
            model_name='articulos',
            old_name='created',
            new_name='actualizado',
        ),
        migrations.RenameField(
            model_name='articulos',
            old_name='author',
            new_name='autor',
        ),
        migrations.RenameField(
            model_name='articulos',
            old_name='categories',
            new_name='categorias',
        ),
        migrations.RenameField(
            model_name='articulos',
            old_name='content',
            new_name='contenido',
        ),
        migrations.RenameField(
            model_name='articulos',
            old_name='updated',
            new_name='creado',
        ),
        migrations.RenameField(
            model_name='articulos',
            old_name='image',
            new_name='imagen',
        ),
        migrations.RenameField(
            model_name='articulos',
            old_name='title',
            new_name='titulo',
        ),
        migrations.RenameField(
            model_name='categoria',
            old_name='created',
            new_name='actualizado',
        ),
        migrations.RenameField(
            model_name='categoria',
            old_name='updated',
            new_name='creado',
        ),
        migrations.RenameField(
            model_name='categoria',
            old_name='type',
            new_name='tipo',
        ),
    ]
